vim.cmd.hi("clear")
vim.o.termguicolors = true
vim.g.colors_name = "ethereal"

local hl = vim.api.nvim_set_hl
hl(0, "@annotation", { link = "PreProc" })
hl(0, "@attribute", { link = "PreProc" })
hl(0, "@boolean", { link = "Boolean" })
hl(0, "@character", { link = "Character" })
hl(0, "@character.printf", { link = "SpecialChar" })
hl(0, "@character.special", { link = "SpecialChar" })
hl(0, "@comment", { link = "Comment" })
hl(0, "@comment.error", { fg = "#faaaa9" })
hl(0, "@comment.hint", { fg = "#a3bfd1" })
hl(0, "@comment.info", { fg = "#7d82d9" })
hl(0, "@comment.note", { fg = "#a3bfd1" })
hl(0, "@comment.todo", { fg = "#c2c4f0" })
hl(0, "@comment.warning", { fg = "#E9BB4F" })
hl(0, "@constant", { link = "Constant" })
hl(0, "@constant.builtin", { link = "Special" })
hl(0, "@constant.macro", { link = "Define" })
hl(0, "@constructor", { fg = "#E9BB4F" })
hl(0, "@constructor.tsx", { fg = "#7d82d9" })
hl(0, "@diff.delta", { link = "DiffChange" })
hl(0, "@diff.minus", { link = "DiffDelete" })
hl(0, "@diff.plus", { link = "DiffAdd" })
hl(0, "@function", { link = "Function" })
hl(0, "@function.builtin", { link = "Special" })
hl(0, "@function.call", { link = "@function" })
hl(0, "@function.macro", { link = "Macro" })
hl(0, "@function.method", { link = "Function" })
hl(0, "@function.method.call", { link = "@function.method" })
hl(0, "@keyword", { fg = "#ead7e7", italic = true })
hl(0, "@keyword.conditional", { link = "Conditional" })
hl(0, "@keyword.coroutine", { link = "@keyword" })
hl(0, "@keyword.debug", { link = "Debug" })
hl(0, "@keyword.directive", { link = "PreProc" })
hl(0, "@keyword.directive.define", { link = "Define" })
hl(0, "@keyword.exception", { link = "Exception" })
hl(0, "@keyword.function", { fg = "#ead7e7" })
hl(0, "@keyword.import", { link = "Include" })
hl(0, "@keyword.operator", { link = "@operator" })
hl(0, "@keyword.repeat", { link = "Repeat" })
hl(0, "@keyword.return", { link = "@keyword" })
hl(0, "@keyword.storage", { link = "StorageClass" })
hl(0, "@label", { fg = "#E9BB4F" })
hl(0, "@lsp.type.class", { link = "Structure" })
hl(0, "@lsp.type.decorator", { link = "Function" })
hl(0, "@lsp.type.enum", { link = "Type" })
hl(0, "@lsp.type.enumMember", { fg = "#eb8b54" })
hl(0, "@lsp.type.function", { link = "Function" })
hl(0, "@lsp.type.interface", { link = "Structure" })
hl(0, "@lsp.type.macro", { link = "Macro" })
hl(0, "@lsp.type.method", { link = "Function" })
hl(0, "@lsp.type.namespace", { link = "Include" })
hl(0, "@lsp.type.parameter", { link = "@variable.parameter" })
hl(0, "@lsp.type.property", { fg = "#dfeaf0" })
hl(0, "@lsp.type.struct", { link = "Structure" })
hl(0, "@lsp.type.type", { link = "Type" })
hl(0, "@lsp.type.typeParameter", { link = "Typedef" })
hl(0, "@lsp.type.variable", { link = "@variable" })
hl(0, "@markup", { link = "@none" })
hl(0, "@markup.emphasis", { italic = true })
hl(0, "@markup.environment", { link = "Macro" })
hl(0, "@markup.environment.name", { link = "Type" })
hl(0, "@markup.heading", { link = "Title" })
hl(0, "@markup.heading.1.markdown", { bold = true, fg = "#faaaa9" })
hl(0, "@markup.heading.2.markdown", { bold = true, fg = "#eb8b54" })
hl(0, "@markup.heading.3.markdown", { bold = true, fg = "#E9BB4F" })
hl(0, "@markup.heading.4.markdown", { bold = true, fg = "#92a593" })
hl(0, "@markup.heading.5.markdown", { bold = true, fg = "#7d82d9" })
hl(0, "@markup.heading.6.markdown", { bold = true, fg = "#ead7e7" })
hl(0, "@markup.italic", { italic = true })
hl(0, "@markup.link", { fg = "#7d82d9", underline = true })
hl(0, "@markup.link.label", { fg = "#7d82d9" })
hl(0, "@markup.link.label.symbol", { link = "Identifier" })
hl(0, "@markup.link.url", { fg = "#a3bfd1", underline = true })
hl(0, "@markup.list", { fg = "#a3bfd1" })
hl(0, "@markup.list.checked", { fg = "#92a593" })
hl(0, "@markup.list.markdown", { bold = true, fg = "#eb8b54" })
hl(0, "@markup.list.unchecked", { fg = "#6d7db6" })
hl(0, "@markup.math", { fg = "#eb8b54" })
hl(0, "@markup.quote", { fg = "#6d7db6", italic = true })
hl(0, "@markup.raw", { fg = "#92a593" })
hl(0, "@markup.raw.block", { fg = "#ffcead" })
hl(0, "@markup.raw.markdown_inline", { bg = "#131a3a", fg = "#7d82d9" })
hl(0, "@markup.strikethrough", { strikethrough = true })
hl(0, "@markup.strong", { bold = true })
hl(0, "@markup.underline", { underline = true })
hl(0, "@module", { link = "Include" })
hl(0, "@module.builtin", { fg = "#faaaa9" })
hl(0, "@namespace.builtin", { link = "@variable.builtin" })
hl(0, "@none", {  })
hl(0, "@number", { link = "Number" })
hl(0, "@number.float", { link = "Float" })
hl(0, "@operator", { fg = "#ffcead" })
hl(0, "@property", { fg = "#dfeaf0" })
hl(0, "@punctuation.bracket", { fg = "#836d66" })
hl(0, "@punctuation.delimiter", { fg = "#836d66" })
hl(0, "@punctuation.special", { fg = "#c2c4f0" })
hl(0, "@punctuation.special.markdown", { fg = "#eb8b54" })
hl(0, "@string", { link = "String" })
hl(0, "@string.documentation", { fg = "#E9BB4F" })
hl(0, "@string.escape", { fg = "#ead7e7" })
hl(0, "@string.regexp", { fg = "#dfeaf0" })
hl(0, "@tag", { link = "Label" })
hl(0, "@tag.attribute", { link = "@property" })
hl(0, "@tag.delimiter", { link = "Delimiter" })
hl(0, "@tag.delimiter.tsx", { fg = "#595ea1" })
hl(0, "@tag.javascript", { fg = "#faaaa9" })
hl(0, "@tag.tsx", { fg = "#faaaa9" })
hl(0, "@type", { link = "Type" })
hl(0, "@type.builtin", { fg = "#ffcead" })
hl(0, "@type.definition", { link = "Typedef" })
hl(0, "@type.qualifier", { link = "@keyword" })
hl(0, "@variable", { fg = "#ffcead" })
hl(0, "@variable.builtin", { bold = true, fg = "#ffcead" })
hl(0, "@variable.member", { fg = "#a3bfd1" })
hl(0, "@variable.parameter", { fg = "#a3bfd1" })
hl(0, "@variable.parameter.builtin", { fg = "#edbf62" })
hl(0, "BlinkCmpDoc", { bg = "#040816", fg = "#ffcead" })
hl(0, "BlinkCmpDocBorder", { bg = "#040816", fg = "#656ab4" })
hl(0, "BlinkCmpKind", { fg = "#ead7e7" })
hl(0, "BlinkCmpKindClass", { fg = "#E9BB4F" })
hl(0, "BlinkCmpKindColor", { fg = "#a3bfd1" })
hl(0, "BlinkCmpKindConstant", { fg = "#eb8b54" })
hl(0, "BlinkCmpKindConstructor", { fg = "#7d82d9" })
hl(0, "BlinkCmpKindEnum", { fg = "#E9BB4F" })
hl(0, "BlinkCmpKindEnumMember", { fg = "#a3bfd1" })
hl(0, "BlinkCmpKindEvent", { fg = "#ead7e7" })
hl(0, "BlinkCmpKindField", { fg = "#a3bfd1" })
hl(0, "BlinkCmpKindFile", { fg = "#ffcead" })
hl(0, "BlinkCmpKindFolder", { fg = "#7d82d9" })
hl(0, "BlinkCmpKindFunction", { fg = "#faaaa9" })
hl(0, "BlinkCmpKindInterface", { fg = "#E9BB4F" })
hl(0, "BlinkCmpKindKeyword", { fg = "#ead7e7" })
hl(0, "BlinkCmpKindMethod", { fg = "#faaaa9" })
hl(0, "BlinkCmpKindModule", { fg = "#7d82d9" })
hl(0, "BlinkCmpKindOperator", { fg = "#a3bfd1" })
hl(0, "BlinkCmpKindProperty", { fg = "#a3bfd1" })
hl(0, "BlinkCmpKindReference", { fg = "#eb8b54" })
hl(0, "BlinkCmpKindSnippet", { fg = "#92a593" })
hl(0, "BlinkCmpKindStruct", { fg = "#E9BB4F" })
hl(0, "BlinkCmpKindText", { fg = "#ffcead" })
hl(0, "BlinkCmpKindTypeParameter", { fg = "#E9BB4F" })
hl(0, "BlinkCmpKindUnit", { fg = "#eb8b54" })
hl(0, "BlinkCmpKindValue", { fg = "#eb8b54" })
hl(0, "BlinkCmpKindVariable", { fg = "#ffcead" })
hl(0, "BlinkCmpLabel", { fg = "#ffcead" })
hl(0, "BlinkCmpLabelDeprecated", { fg = "#6d7db6", strikethrough = true })
hl(0, "BlinkCmpLabelDescription", { fg = "#6d7db6" })
hl(0, "BlinkCmpLabelDetail", { fg = "#6d7db6" })
hl(0, "BlinkCmpLabelMatch", { bold = true, fg = "#7d82d9" })
hl(0, "BlinkCmpMenu", { bg = "#040816", fg = "#ffcead" })
hl(0, "BlinkCmpMenuBorder", { bg = "#040816", fg = "#656ab4" })
hl(0, "BlinkCmpMenuSelection", { bg = "#586698" })
hl(0, "BlinkCmpSignatureHelp", { bg = "#040816", fg = "#ffcead" })
hl(0, "BlinkCmpSignatureHelpActiveParameter", { bold = true, fg = "#7d82d9" })
hl(0, "BlinkCmpSignatureHelpBorder", { bg = "#040816", fg = "#656ab4" })
hl(0, "Boolean", { fg = "#eb8b54" })
hl(0, "Character", { fg = "#92a593" })
hl(0, "ColorColumn", { bg = "#060b1e" })
hl(0, "Comment", { fg = "#6d7db6", italic = true })
hl(0, "CommentBold", { bold = true, fg = "#6d7db6" })
hl(0, "CommentItalic", { fg = "#6d7db6", italic = true })
hl(0, "CommentNormal", { fg = "#6d7db6", italic = true })
hl(0, "CommentURL", { fg = "#7d82d9", underline = true })
hl(0, "Conceal", { fg = "#6d7db6" })
hl(0, "Conditional", { fg = "#ead7e7" })
hl(0, "ConformDone", { fg = "#92a593" })
hl(0, "ConformError", { fg = "#faaaa9" })
hl(0, "ConformProgress", { fg = "#7d82d9" })
hl(0, "Constant", { fg = "#f7dc9c" })
hl(0, "CurSearch", { link = "IncSearch" })
hl(0, "Cursor", { bg = "#ffcead", fg = "#060B1E" })
hl(0, "CursorColumn", { bg = "#131a3a" })
hl(0, "CursorIM", { bg = "#ffcead", fg = "#060B1E" })
hl(0, "CursorLine", { bg = "#38323b" })
hl(0, "CursorLineNr", { bold = true, fg = "#eb8b54" })
hl(0, "DapBreakpoint", { fg = "#faaaa9" })
hl(0, "DapBreakpointCondition", { fg = "#E9BB4F" })
hl(0, "DapBreakpointRejected", { fg = "#6d7db6" })
hl(0, "DapLogPoint", { fg = "#7d82d9" })
hl(0, "DapStopped", { fg = "#92a593" })
hl(0, "DapStoppedLine", { bg = "#332e28" })
hl(0, "DapUIBreakpointsCurrentLine", { bold = true, fg = "#92a593" })
hl(0, "DapUIBreakpointsDisabledLine", { fg = "#6d7db6" })
hl(0, "DapUIBreakpointsInfo", { fg = "#92a593" })
hl(0, "DapUIBreakpointsPath", { fg = "#a3bfd1" })
hl(0, "DapUIDecoration", { fg = "#7d82d9" })
hl(0, "DapUIFloatBorder", { fg = "#656ab4" })
hl(0, "DapUILineNumber", { fg = "#a3bfd1" })
hl(0, "DapUIModifiedValue", { bold = true, fg = "#a3bfd1" })
hl(0, "DapUIPlayPause", { fg = "#92a593" })
hl(0, "DapUIRestart", { fg = "#92a593" })
hl(0, "DapUIScope", { fg = "#a3bfd1" })
hl(0, "DapUISource", { fg = "#ead7e7" })
hl(0, "DapUIStepBack", { fg = "#a3bfd1" })
hl(0, "DapUIStepInto", { fg = "#a3bfd1" })
hl(0, "DapUIStepOut", { fg = "#a3bfd1" })
hl(0, "DapUIStepOver", { fg = "#a3bfd1" })
hl(0, "DapUIStop", { fg = "#faaaa9" })
hl(0, "DapUIStoppedThread", { fg = "#a3bfd1" })
hl(0, "DapUIThread", { fg = "#92a593" })
hl(0, "DapUIType", { fg = "#ead7e7" })
hl(0, "DapUIValue", { fg = "#ffcead" })
hl(0, "DapUIVariable", { fg = "#ffcead" })
hl(0, "DapUIWatchesEmpty", { fg = "#faaaa9" })
hl(0, "DapUIWatchesError", { fg = "#faaaa9" })
hl(0, "DapUIWatchesValue", { fg = "#92a593" })
hl(0, "Debug", { fg = "#faaaa9" })
hl(0, "Define", { fg = "#ead7e7" })
hl(0, "Delimiter", { fg = "#ffcead" })
hl(0, "DiagnosticError", { fg = "#faaaa9" })
hl(0, "DiagnosticHint", { fg = "#a3bfd1" })
hl(0, "DiagnosticInfo", { fg = "#7d82d9" })
hl(0, "DiagnosticUnderlineError", { sp = "#ED5B5A", undercurl = true })
hl(0, "DiagnosticUnderlineHint", { sp = "#a3bfd1", undercurl = true })
hl(0, "DiagnosticUnderlineInfo", { sp = "#7d82d9", undercurl = true })
hl(0, "DiagnosticUnderlineWarn", { sp = "#E9BB4F", undercurl = true })
hl(0, "DiagnosticUnnecessary", { fg = "#6d7db6" })
hl(0, "DiagnosticVirtualTextError", { bg = "#1d1324", fg = "#faaaa9" })
hl(0, "DiagnosticVirtualTextHint", { bg = "#161d30", fg = "#a3bfd1" })
hl(0, "DiagnosticVirtualTextInfo", { bg = "#121731", fg = "#c2c4f0" })
hl(0, "DiagnosticVirtualTextWarn", { bg = "#1d1d23", fg = "#E9BB4F" })
hl(0, "DiagnosticWarn", { fg = "#E9BB4F" })
hl(0, "DiffAdd", { bg = "#29323b" })
hl(0, "DiffChange", { bg = "#0b1026" })
hl(0, "DiffDelete", { bg = "#401f2d" })
hl(0, "DiffText", { bg = "#252e56" })
hl(0, "DiffviewFilePanelCounter", { fg = "#ead7e7" })
hl(0, "DiffviewFilePanelDeletions", { fg = "#faaaa9" })
hl(0, "DiffviewFilePanelFileName", { fg = "#ffcead" })
hl(0, "DiffviewFilePanelInsertions", { fg = "#92a593" })
hl(0, "DiffviewFilePanelPath", { fg = "#6d7db6" })
hl(0, "DiffviewFilePanelTitle", { bold = true, fg = "#7d82d9" })
hl(0, "DiffviewPrimary", { bold = true, fg = "#7d82d9" })
hl(0, "DiffviewSecondary", { fg = "#ead7e7" })
hl(0, "DiffviewStatusAdded", { fg = "#92a593" })
hl(0, "DiffviewStatusBroken", { fg = "#faaaa9" })
hl(0, "DiffviewStatusCopied", { fg = "#7d82d9" })
hl(0, "DiffviewStatusDeleted", { fg = "#faaaa9" })
hl(0, "DiffviewStatusModified", { fg = "#7d82d9" })
hl(0, "DiffviewStatusRenamed", { fg = "#7d82d9" })
hl(0, "DiffviewStatusTypeChange", { fg = "#7d82d9" })
hl(0, "DiffviewStatusUnknown", { fg = "#faaaa9" })
hl(0, "DiffviewStatusUnmerged", { fg = "#E9BB4F" })
hl(0, "DiffviewStatusUntracked", { fg = "#7d82d9" })
hl(0, "Directory", { bold = true, fg = "#7d82d9" })
hl(0, "EndOfBuffer", { fg = "#060B1E" })
hl(0, "Error", { bold = true, fg = "#faaaa9" })
hl(0, "ErrorMsg", { bold = true, fg = "#faaaa9" })
hl(0, "Exception", { fg = "#ead7e7" })
hl(0, "FidgetTask", { fg = "#6d7db6" })
hl(0, "FidgetTitle", { bold = true, fg = "#7d82d9" })
hl(0, "FlashBackdrop", { fg = "#6d7db6" })
hl(0, "FlashCurrent", { bg = "#eb8b54", bold = true, fg = "#060b1e" })
hl(0, "FlashLabel", { bg = "#c89dc1", bold = true, fg = "#060b1e" })
hl(0, "FlashMatch", { bg = "#131a3a", bold = true, fg = "#a3bfd1" })
hl(0, "FlashPrompt", { link = "NormalFloat" })
hl(0, "Float", { fg = "#eb8b54" })
hl(0, "FloatBorder", { bg = "#040816", fg = "#656ab4" })
hl(0, "FloatTitle", { bg = "#040816", bold = true, fg = "#656ab4" })
hl(0, "FoldColumn", { bg = "#060B1E", fg = "#6d7db6" })
hl(0, "Folded", { bg = "#1f1f2c", fg = "#c2c4f0", italic = true })
hl(0, "Function", { bold = true, fg = "#7d82d9" })
hl(0, "GitSignsAdd", { fg = "#92a593" })
hl(0, "GitSignsChange", { fg = "#eb8b54" })
hl(0, "GitSignsDelete", { fg = "#faaaa9" })
hl(0, "IblIndent", { fg = "#6d7db6", nocombine = true })
hl(0, "IblScope", { fg = "#7d82d9", nocombine = true })
hl(0, "Identifier", { fg = "#dfeaf0" })
hl(0, "Ignore", { fg = "#6d7db6" })
hl(0, "IncSearch", { bg = "#eb8b54", bold = true, fg = "#060b1e" })
hl(0, "Include", { fg = "#7d82d9" })
hl(0, "Keyword", { bold = true, fg = "#ead7e7", italic = true })
hl(0, "Label", { fg = "#E9BB4F" })
hl(0, "LineNr", { fg = "#6d7db6" })
hl(0, "LineNrAbove", { fg = "#6d7db6" })
hl(0, "LineNrBelow", { fg = "#6d7db6" })
hl(0, "LintError", { fg = "#faaaa9" })
hl(0, "LintHint", { fg = "#a3bfd1" })
hl(0, "LintInfo", { fg = "#7d82d9" })
hl(0, "LintWarning", { fg = "#E9BB4F" })
hl(0, "LspCodeLens", { fg = "#6d7db6" })
hl(0, "LspInfoBorder", { bg = "#040816", fg = "#656ab4" })
hl(0, "LspInlayHint", { bg = "#10162d", fg = "#6d7db6" })
hl(0, "LspReferenceRead", { bg = "#252e56", fg = "#ffcead" })
hl(0, "LspReferenceText", { bg = "#252e56", fg = "#ffcead" })
hl(0, "LspReferenceWrite", { bg = "#252e56", bold = true, fg = "#E9BB4F" })
hl(0, "LspSignatureActiveParameter", { bold = true, fg = "#eb8b54" })
hl(0, "Macro", { fg = "#a3bfd1" })
hl(0, "MasonError", { fg = "#faaaa9" })
hl(0, "MasonHeader", { bg = "#7d82d9", bold = true, fg = "#060b1e" })
hl(0, "MasonHeaderSecondary", { bg = "#c89dc1", bold = true, fg = "#060b1e" })
hl(0, "MasonHeading", { bold = true, fg = "#7d82d9" })
hl(0, "MasonHighlight", { fg = "#7d82d9" })
hl(0, "MasonHighlightBlock", { bg = "#7d82d9", fg = "#060b1e" })
hl(0, "MasonHighlightBlockBold", { bg = "#7d82d9", bold = true, fg = "#060b1e" })
hl(0, "MasonHighlightBlockBoldSecondary", { bg = "#c89dc1", bold = true, fg = "#060b1e" })
hl(0, "MasonHighlightBlockSecondary", { bg = "#c89dc1", fg = "#060b1e" })
hl(0, "MasonHighlightSecondary", { fg = "#ead7e7" })
hl(0, "MasonMuted", { fg = "#6d7db6" })
hl(0, "MasonMutedBlock", { bg = "#040816", fg = "#ffcead" })
hl(0, "MasonMutedBlockBold", { bg = "#040816", bold = true, fg = "#ffcead" })
hl(0, "MasonWarning", { fg = "#E9BB4F" })
hl(0, "MatchParen", { bold = true, fg = "#eb8b54" })
hl(0, "MiniCompletionActiveParameter", { underline = true })
hl(0, "MiniCursorword", { bg = "#131a3a" })
hl(0, "MiniCursorwordCurrent", { bg = "#131a3a" })
hl(0, "MiniIndentscopePrefix", { nocombine = true })
hl(0, "MiniIndentscopeSymbol", { fg = "#7d82d9", nocombine = true })
hl(0, "MiniJump", { bg = "#c89dc1", fg = "#060b1e" })
hl(0, "MiniJump2dSpot", { bold = true, fg = "#ead7e7", nocombine = true })
hl(0, "MiniStarterCurrent", { nocombine = true })
hl(0, "MiniStarterFooter", { fg = "#E9BB4F", italic = true })
hl(0, "MiniStarterHeader", { bold = true, fg = "#7d82d9" })
hl(0, "MiniStarterInactive", { fg = "#6d7db6" })
hl(0, "MiniStarterItem", { fg = "#ffcead" })
hl(0, "MiniStarterItemBullet", { fg = "#656ab4" })
hl(0, "MiniStarterItemPrefix", { fg = "#E9BB4F" })
hl(0, "MiniStarterQuery", { fg = "#7d82d9" })
hl(0, "MiniStarterSection", { bold = true, fg = "#7d82d9" })
hl(0, "MiniStatuslineDevinfo", { bg = "#131a3a", fg = "#6d7db6" })
hl(0, "MiniStatuslineFileinfo", { bg = "#131a3a", fg = "#6d7db6" })
hl(0, "MiniStatuslineFilename", { bg = "#6d7db6", fg = "#6d7db6" })
hl(0, "MiniStatuslineInactive", { bg = "#040816", fg = "#7d82d9" })
hl(0, "MiniStatuslineModeCommand", { bg = "#E9BB4F", bold = true, fg = "#060b1e" })
hl(0, "MiniStatuslineModeInsert", { bg = "#92a593", bold = true, fg = "#060b1e" })
hl(0, "MiniStatuslineModeNormal", { bg = "#7d82d9", bold = true, fg = "#060b1e" })
hl(0, "MiniStatuslineModeOther", { bg = "#a3bfd1", bold = true, fg = "#060b1e" })
hl(0, "MiniStatuslineModeReplace", { bg = "#ED5B5A", bold = true, fg = "#060b1e" })
hl(0, "MiniStatuslineModeVisual", { bg = "#c89dc1", bold = true, fg = "#060b1e" })
hl(0, "MiniSurround", { bg = "#eb8b54", fg = "#060b1e" })
hl(0, "MiniTablineCurrent", { bg = "#131a3a", bold = true, fg = "#ffcead" })
hl(0, "MiniTablineFill", { bg = "#060b1e" })
hl(0, "MiniTablineHidden", { bg = "#040816", fg = "#6d7db6" })
hl(0, "MiniTablineModifiedCurrent", { bg = "#131a3a", bold = true, fg = "#E9BB4F" })
hl(0, "MiniTablineModifiedHidden", { bg = "#040816", fg = "#6d7db6" })
hl(0, "MiniTablineModifiedVisible", { bg = "#040816", fg = "#E9BB4F" })
hl(0, "MiniTablineTabpagesection", { bg = "#7d82d9", bold = true, fg = "#060b1e" })
hl(0, "MiniTablineVisible", { bg = "#040816", fg = "#ffcead" })
hl(0, "MiniTestEmphasis", { bold = true })
hl(0, "MiniTestFail", { bold = true, fg = "#faaaa9" })
hl(0, "MiniTestPass", { bold = true, fg = "#92a593" })
hl(0, "MiniTrailspace", { bg = "#ED5B5A" })
hl(0, "ModeMsg", { bold = true, fg = "#6d7db6" })
hl(0, "MoreMsg", { bold = true, fg = "#7d82d9" })
hl(0, "MsgArea", { fg = "#6d7db6" })
hl(0, "NeoTreeDimText", { fg = "#6d7db6" })
hl(0, "NeoTreeDirectoryIcon", { fg = "#7d82d9" })
hl(0, "NeoTreeDirectoryName", { fg = "#7d82d9" })
hl(0, "NeoTreeFileName", { fg = "#ffcead" })
hl(0, "NeoTreeFileNameOpened", { fg = "#ffcead" })
hl(0, "NeoTreeGitAdded", { fg = "#92a593" })
hl(0, "NeoTreeGitConflict", { fg = "#faaaa9" })
hl(0, "NeoTreeGitDeleted", { fg = "#faaaa9" })
hl(0, "NeoTreeGitIgnored", { fg = "#6d7db6" })
hl(0, "NeoTreeGitModified", { fg = "#eb8b54" })
hl(0, "NeoTreeGitRenamed", { fg = "#eb8b54" })
hl(0, "NeoTreeGitStaged", { fg = "#92a593" })
hl(0, "NeoTreeGitUnstaged", { fg = "#eb8b54" })
hl(0, "NeoTreeGitUntracked", { fg = "#eb8b54" })
hl(0, "NeoTreeNormal", { bg = "#040816", fg = "#ffcead" })
hl(0, "NeoTreeNormalNC", { bg = "#040816", fg = "#ffcead" })
hl(0, "NeoTreeRootName", { bold = true, fg = "#7d82d9" })
hl(0, "NeoTreeSymbolicLinkTarget", { fg = "#a3bfd1" })
hl(0, "NeoTreeTabActive", { bg = "#040816", bold = true, fg = "#7d82d9" })
hl(0, "NeoTreeTabInactive", { bg = "#040918", fg = "#6d7db6" })
hl(0, "NeoTreeTabSeparatorActive", { bg = "#040816", fg = "#7d82d9" })
hl(0, "NeoTreeTabSeparatorInactive", { bg = "#040918", fg = "#060B1E" })
hl(0, "NoiceCmdline", { bg = "#040816" })
hl(0, "NoiceCmdlineIcon", { fg = "#7d82d9" })
hl(0, "NoiceCmdlineIconSearch", { fg = "#E9BB4F" })
hl(0, "NoiceCmdlinePopup", { bg = "#040816" })
hl(0, "NoiceCmdlinePopupBorder", { bg = "#040816", fg = "#656ab4" })
hl(0, "NoiceCmdlinePopupBorderSearch", { bg = "#040816", fg = "#656ab4" })
hl(0, "NoiceCompletionItemKindClass", { fg = "#E9BB4F" })
hl(0, "NoiceCompletionItemKindConstant", { fg = "#eb8b54" })
hl(0, "NoiceCompletionItemKindConstructor", { fg = "#7d82d9" })
hl(0, "NoiceCompletionItemKindDefault", { fg = "#6d7db6" })
hl(0, "NoiceCompletionItemKindEnum", { fg = "#E9BB4F" })
hl(0, "NoiceCompletionItemKindEnumMember", { fg = "#a3bfd1" })
hl(0, "NoiceCompletionItemKindEvent", { fg = "#ead7e7" })
hl(0, "NoiceCompletionItemKindField", { fg = "#a3bfd1" })
hl(0, "NoiceCompletionItemKindFunction", { fg = "#faaaa9" })
hl(0, "NoiceCompletionItemKindInterface", { fg = "#E9BB4F" })
hl(0, "NoiceCompletionItemKindKeyword", { fg = "#ead7e7" })
hl(0, "NoiceCompletionItemKindMethod", { fg = "#faaaa9" })
hl(0, "NoiceCompletionItemKindModule", { fg = "#7d82d9" })
hl(0, "NoiceCompletionItemKindOperator", { fg = "#a3bfd1" })
hl(0, "NoiceCompletionItemKindProperty", { fg = "#a3bfd1" })
hl(0, "NoiceCompletionItemKindReference", { fg = "#eb8b54" })
hl(0, "NoiceCompletionItemKindSnippet", { fg = "#92a593" })
hl(0, "NoiceCompletionItemKindStruct", { fg = "#E9BB4F" })
hl(0, "NoiceCompletionItemKindTypeParameter", { fg = "#E9BB4F" })
hl(0, "NoiceCompletionItemKindUnit", { fg = "#eb8b54" })
hl(0, "NoiceCompletionItemKindValue", { fg = "#eb8b54" })
hl(0, "NoiceCompletionItemKindVariable", { fg = "#ffcead" })
hl(0, "NoiceConfirm", { bg = "#040816" })
hl(0, "NoiceConfirmBorder", { bg = "#040816", fg = "#656ab4" })
hl(0, "NonText", { fg = "#6d7db6" })
hl(0, "Normal", { bg = "#060B1E", fg = "#ffcead" })
hl(0, "NormalFloat", { bg = "#040816", fg = "#ffcead" })
hl(0, "NormalNC", { bg = "#060B1E", fg = "#ffcead" })
hl(0, "NormalSB", { bg = "#040816", fg = "#ffcead" })
hl(0, "Number", { fg = "#eb8b54" })
hl(0, "NvimTreeFolderIcon", { bg = "NONE", fg = "#7d82d9" })
hl(0, "NvimTreeGitDeleted", { fg = "#faaaa9" })
hl(0, "NvimTreeGitDirty", { fg = "#eb8b54" })
hl(0, "NvimTreeGitIgnored", { fg = "#6d7db6" })
hl(0, "NvimTreeGitMerge", { fg = "#faaaa9" })
hl(0, "NvimTreeGitNew", { fg = "#92a593" })
hl(0, "NvimTreeGitRenamed", { fg = "#eb8b54" })
hl(0, "NvimTreeGitStaged", { fg = "#92a593" })
hl(0, "NvimTreeImageFile", { fg = "#ffcead" })
hl(0, "NvimTreeIndentMarker", { fg = "#6d7db6" })
hl(0, "NvimTreeNormal", { bg = "#040816", fg = "#ffcead" })
hl(0, "NvimTreeNormalNC", { bg = "#040816", fg = "#ffcead" })
hl(0, "NvimTreeOpenedFile", { bg = "#131a3a" })
hl(0, "NvimTreeRootFolder", { bold = true, fg = "#7d82d9" })
hl(0, "NvimTreeSpecialFile", { fg = "#ead7e7", underline = true })
hl(0, "NvimTreeSymlink", { fg = "#7d82d9" })
hl(0, "NvimTreeWinSeparator", { bg = "#040816", fg = "#040816" })
hl(0, "Operator", { fg = "#ffcead" })
hl(0, "Pmenu", { bg = "#040816", fg = "#ffcead" })
hl(0, "PmenuMatch", { bg = "#040816", fg = "#7d82d9" })
hl(0, "PmenuMatchSel", { bg = "#586698", fg = "#7d82d9" })
hl(0, "PmenuSbar", { bg = "#11121e" })
hl(0, "PmenuSel", { bg = "#586698" })
hl(0, "PmenuThumb", { bg = "#6d7db6" })
hl(0, "PreCondit", { fg = "#a3bfd1" })
hl(0, "PreProc", { fg = "#a3bfd1" })
hl(0, "Question", { bold = true, fg = "#7d82d9" })
hl(0, "QuickFixLine", { bg = "#252e56", bold = true })
hl(0, "Repeat", { fg = "#ead7e7" })
hl(0, "Search", { bg = "#363b69", bold = true, fg = "#ffcead" })
hl(0, "SignColumn", { bg = "#060B1E", fg = "#6d7db6" })
hl(0, "SignColumnSB", { bg = "#040816", fg = "#6d7db6" })
hl(0, "SnacksBackdrop", { bg = "#040816" })
hl(0, "SnacksNormal", { bg = "#040816", fg = "#ffcead" })
hl(0, "SnacksNormalNC", { bg = "#040816", fg = "#ffcead" })
hl(0, "SnacksNotifierBorderDebug", { fg = "#6d7db6" })
hl(0, "SnacksNotifierBorderError", { fg = "#faaaa9" })
hl(0, "SnacksNotifierBorderInfo", { fg = "#7d82d9" })
hl(0, "SnacksNotifierBorderTrace", { fg = "#ead7e7" })
hl(0, "SnacksNotifierBorderWarn", { fg = "#E9BB4F" })
hl(0, "SnacksNotifierDebug", { fg = "#6d7db6" })
hl(0, "SnacksNotifierError", { fg = "#faaaa9" })
hl(0, "SnacksNotifierIconDebug", { fg = "#6d7db6" })
hl(0, "SnacksNotifierIconError", { fg = "#faaaa9" })
hl(0, "SnacksNotifierIconInfo", { fg = "#7d82d9" })
hl(0, "SnacksNotifierIconTrace", { fg = "#ead7e7" })
hl(0, "SnacksNotifierIconWarn", { fg = "#E9BB4F" })
hl(0, "SnacksNotifierInfo", { fg = "#7d82d9" })
hl(0, "SnacksNotifierTitleDebug", { bold = true, fg = "#6d7db6" })
hl(0, "SnacksNotifierTitleError", { bold = true, fg = "#faaaa9" })
hl(0, "SnacksNotifierTitleInfo", { bold = true, fg = "#7d82d9" })
hl(0, "SnacksNotifierTitleTrace", { bold = true, fg = "#ead7e7" })
hl(0, "SnacksNotifierTitleWarn", { bold = true, fg = "#E9BB4F" })
hl(0, "SnacksNotifierTrace", { fg = "#ead7e7" })
hl(0, "SnacksNotifierWarn", { fg = "#E9BB4F" })
hl(0, "SnacksWinBar", { bg = "#040816", fg = "#ffcead" })
hl(0, "SnacksWinBarNC", { bg = "#040816", fg = "#6d7db6" })
hl(0, "Special", { fg = "#a3bfd1" })
hl(0, "SpecialChar", { fg = "#faaaa9" })
hl(0, "SpecialComment", { fg = "#6d7db6", italic = true })
hl(0, "SpecialKey", { fg = "#6d7db6" })
hl(0, "SpellBad", { sp = "#ED5B5A", undercurl = true })
hl(0, "SpellCap", { sp = "#E9BB4F", undercurl = true })
hl(0, "SpellLocal", { sp = "#7d82d9", undercurl = true })
hl(0, "SpellRare", { sp = "#a3bfd1", undercurl = true })
hl(0, "Statement", { bold = true, fg = "#7d82d9" })
hl(0, "StatusLine", { bg = "#040816", fg = "#ffcead" })
hl(0, "StatusLineNC", { bg = "#040816", fg = "#6d7db6" })
hl(0, "StorageClass", { fg = "#E9BB4F" })
hl(0, "String", { fg = "#92a593" })
hl(0, "Structure", { fg = "#E9BB4F" })
hl(0, "Substitute", { bg = "#ED5B5A", fg = "#060B1E" })
hl(0, "TabLine", { bg = "#040816", fg = "#6d7db6" })
hl(0, "TabLineFill", { bg = "#060b1e" })
hl(0, "TabLineSel", { bg = "#7d82d9", fg = "#060b1e" })
hl(0, "Tag", { fg = "#faaaa9" })
hl(0, "TelescopeBorder", { link = "FloatBorder" })
hl(0, "TelescopeMatching", { bold = true, fg = "#a3bfd1" })
hl(0, "TelescopeMultiSelection", { bg = "#131a3a", fg = "#ffcead" })
hl(0, "TelescopeNormal", { link = "NormalFloat" })
hl(0, "TelescopePreviewBorder", { link = "FloatBorder" })
hl(0, "TelescopePreviewLine", { bg = "#131a3a" })
hl(0, "TelescopePreviewMatch", { bg = "#131a3a", fg = "#a3bfd1" })
hl(0, "TelescopePreviewNormal", { link = "NormalFloat" })
hl(0, "TelescopePreviewTitle", { bold = true, fg = "#7d82d9" })
hl(0, "TelescopePromptBorder", { bg = "#040816", fg = "#656ab4" })
hl(0, "TelescopePromptNormal", { bg = "#040816" })
hl(0, "TelescopePromptPrefix", { fg = "#ffcead" })
hl(0, "TelescopePromptTitle", { bold = true, fg = "#7d82d9" })
hl(0, "TelescopeResultsBorder", { link = "FloatBorder" })
hl(0, "TelescopeResultsDirectory", { bold = true, fg = "#7d82d9" })
hl(0, "TelescopeResultsNormal", { link = "NormalFloat" })
hl(0, "TelescopeResultsTitle", { bold = true, fg = "#faaaa9" })
hl(0, "TelescopeSelection", { bg = "#131a3a", fg = "#ffcead" })
hl(0, "TelescopeSelectionCaret", { bg = "#131a3a", fg = "#ffcead" })
hl(0, "Title", { bold = true, fg = "#7d82d9" })
hl(0, "Todo", { bg = "#E9BB4F", bold = true, fg = "#060B1E" })
hl(0, "TroubleCode", { fg = "#6d7db6" })
hl(0, "TroubleCount", { bg = "#6d7db6", fg = "#ead7e7" })
hl(0, "TroubleFile", { fg = "#7d82d9" })
hl(0, "TroubleFoldIcon", { fg = "#6d7db6" })
hl(0, "TroubleIndent", { fg = "#6d7db6" })
hl(0, "TroubleLocation", { fg = "#6d7db6" })
hl(0, "TroubleNormal", { bg = "#040816", fg = "#ffcead" })
hl(0, "TroubleSignError", { fg = "#faaaa9" })
hl(0, "TroubleSignHint", { fg = "#a3bfd1" })
hl(0, "TroubleSignInformation", { fg = "#7d82d9" })
hl(0, "TroubleSignOther", { fg = "#ead7e7" })
hl(0, "TroubleSignWarning", { fg = "#E9BB4F" })
hl(0, "TroubleText", { fg = "#6d7db6" })
hl(0, "TroubleTextInformation", { fg = "#7d82d9" })
hl(0, "Type", { bold = true, fg = "#E9BB4F" })
hl(0, "Typedef", { fg = "#E9BB4F" })
hl(0, "Underlined", { underline = true })
hl(0, "VertSplit", { fg = "#6d7db6" })
hl(0, "Visual", { bg = "#252e56" })
hl(0, "VisualNOS", { bg = "#252e56" })
hl(0, "WarningMsg", { bold = true, fg = "#E9BB4F" })
hl(0, "WhichKey", { fg = "#a3bfd1" })
hl(0, "WhichKeyBorder", { bg = "#040816", fg = "#656ab4" })
hl(0, "WhichKeyDesc", { fg = "#ead7e7" })
hl(0, "WhichKeyFloat", { bg = "#040816" })
hl(0, "WhichKeyGroup", { bold = true, fg = "#7d82d9" })
hl(0, "WhichKeySeparator", { fg = "#6d7db6" })
hl(0, "WhichKeyValue", { fg = "#6d7db6" })
hl(0, "Whitespace", { fg = "#6d7db6" })
hl(0, "WildMenu", { bg = "#252e56" })
hl(0, "WinBar", { link = "StatusLine" })
hl(0, "WinBarNC", { link = "StatusLineNC" })
hl(0, "WinSeparator", { bold = true, fg = "#6d7db6" })
hl(0, "debugBreakpoint", { bg = "#121731", fg = "#7d82d9" })
hl(0, "debugPC", { bg = "#040816" })
hl(0, "diffAdded", { bg = "#29323b", fg = "#c4cfc4" })
hl(0, "diffChanged", { bg = "#0b1026", fg = "#eb8b54" })
hl(0, "diffFile", { fg = "#7d82d9" })
hl(0, "diffIndexLine", { fg = "#ead7e7" })
hl(0, "diffLine", { fg = "#6d7db6" })
hl(0, "diffNewFile", { bg = "#29323b", fg = "#7d82d9" })
hl(0, "diffOldFile", { bg = "#401f2d", fg = "#7d82d9" })
hl(0, "diffRemoved", { bg = "#401f2d", fg = "#faaaa9" })
hl(0, "dosIniLabel", { link = "@property" })
hl(0, "gitcommitBranch", { bold = true, fg = "#eb8b54" })
hl(0, "gitcommitComment", { fg = "#6d7db6", italic = true })
hl(0, "gitcommitDiscarded", { fg = "#6d7db6" })
hl(0, "gitcommitDiscardedFile", { bold = true, fg = "#faaaa9" })
hl(0, "gitcommitDiscardedType", { fg = "#7d82d9" })
hl(0, "gitcommitHeader", { fg = "#ead7e7" })
hl(0, "gitcommitOverflow", { fg = "#faaaa9" })
hl(0, "gitcommitSelected", { fg = "#6d7db6" })
hl(0, "gitcommitSelectedFile", { bold = true, fg = "#92a593" })
hl(0, "gitcommitSelectedType", { fg = "#7d82d9" })
hl(0, "gitcommitSummary", { fg = "#92a593" })
hl(0, "gitcommitUnmergedFile", { bold = true, fg = "#faaaa9" })
hl(0, "gitcommitUnmergedType", { fg = "#7d82d9" })
hl(0, "gitcommitUntracked", { fg = "#6d7db6" })
hl(0, "gitcommitUntrackedFile", { fg = "#E9BB4F" })
hl(0, "healthError", { fg = "#faaaa9" })
hl(0, "healthSuccess", { fg = "#92a593" })
hl(0, "healthWarning", { fg = "#E9BB4F" })
hl(0, "helpCommand", { bg = "#1f1f2c", fg = "#7d82d9" })
hl(0, "htmlH1", { bold = true, fg = "#ead7e7" })
hl(0, "htmlH2", { bold = true, fg = "#7d82d9" })
hl(0, "lCursor", { bg = "#ffcead", fg = "#060B1E" })
hl(0, "qfFileName", { fg = "#7d82d9" })
hl(0, "qfLineNr", { fg = "#6d7db6" })

vim.g.terminal_color_0 = "#060b1e"
vim.g.terminal_color_1 = "#ED5B5A"
vim.g.terminal_color_2 = "#92a593"
vim.g.terminal_color_3 = "#E9BB4F"
vim.g.terminal_color_4 = "#7d82d9"
vim.g.terminal_color_5 = "#c89dc1"
vim.g.terminal_color_6 = "#a3bfd1"
vim.g.terminal_color_7 = "#6d7db6"
vim.g.terminal_color_8 = "#131a3a"
vim.g.terminal_color_9 = "#faaaa9"
vim.g.terminal_color_10 = "#c4cfc4"
vim.g.terminal_color_11 = "#f7dc9c"
vim.g.terminal_color_12 = "#c2c4f0"
vim.g.terminal_color_13 = "#ead7e7"
vim.g.terminal_color_14 = "#dfeaf0"
vim.g.terminal_color_15 = "#ffcead"
